version: '3.9'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    ports:
      - 8123:8123
    volumes:
      - ./config:/config
      - ../custom_components/alpha_innotec:/config/custom_components/alpha_innotec
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../tests/fixtures:/var/www
